### ISSUE TITLE
gsha256sum: command not found

### ISSUE THREAD

**Issue by retgits** [michaeldfallen/butler#10]
Hi,

On my Mac (10.10.3) executing butler returns an error "line 44: gsha256sum: command not found". I was able to fix it by changing gsha256sum into shasum

**Comment by michaeldfallen** [comment]
Did you install butler through brew?

**Comment by retgits** [comment]
Ah I see my flaw here, I didn't install it through brew and when I checked your recipe just now I see the install for gsha256sum as well.

Sorry

**Comment by michaeldfallen** [comment]
No problem. I'll update the readme to include a section on dependancies.
