### ISSUE TITLE
Butler fails to run

### ISSUE THREAD

**Issue by tkovacs-dev** [michaeldfallen/butler#6]
On OS X 10.10.3, installing and running the 'butler' command fails, see below.

$ brew install butler
==> Installing butler from michaeldfallen/homebrew-formula
==> Downloading https://github.com/michaeldfallen/butler/archive/0.5.tar.gz
###### ################################################################## 100.0%

==> To enable completion add:
==>   source "$(butler --init-completion)"
==> To your ~/.bashrc or ~/.zshrc
🍺  /usr/local/Cellar/butler/0.5: 8 files, 36K, built in 2 seconds

$ butler
/usr/local/bin/butler: line 14: greadlink: command not found
/usr/local/bin/butler: line 21: /usr/local/bin/butler-base.sh: No such file or directory

**Comment by Boldewyn** [comment]
`brew install coreutils` seems to be necessary before: http://stackoverflow.com/a/4031502/113195

**Comment by a1ee9b** [comment]
Had the same problem, @Boldewyn solution fixed it.

@michaeldfallen maybe add `coreutils` as a dependency for mac to the readme.

**Comment by michaeldfallen** [comment]
Ah, I'll update the formula to require `coreutils`. Sorry about that.

**Comment by michaeldfallen** [comment]
Formula is updated. Run:

```
> brew update
> brew install michaeldfallen/formula/butler
```
