### ISSUE TITLE
butler is incompatible with sh on Debian/Ubuntu

### ISSUE THREAD

**Issue by Boldewyn** [michaeldfallen/butler#7]
`butler` starts with

```
#! /usr/bin/env sh
```

However, on Debian and Ubuntu, `sh` is aliased to `dash`, not `bash`. That means, invoking `butler` yields:

```
$ ./butler
./butler: 8: ./butler: [[: not found
./butler: 16: ./butler: [[: not found
./butler: 21: ./butler: source: not found
./butler: 23: ./butler: butler_exec: not found
```

A fix would be the shebang line

```
#! /usr/bin/env bash
```

However, I do not know, if `zsh` users will then encounter problems.

**Comment by michaeldfallen** [comment]
I've switched to bash and the tests pass on my machine using both zsh and bash as my interactive terminal. Will grab an ubuntu vm and test it out there.

Thanks for reporting this.

**Comment by michaeldfallen** [comment]
This should be solved on the newest version. Closing for now.
